### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by xycjscs** [azz212/chatgpt-on-wechat-ipad#2]
api 发送失败HTTPSConnectionPool(host='xxx', port=443): Max retries exceeded with url: /api/open/room/list (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1133)')))

**Comment by azz212** [comment]
需要申请ipad协议token，3天免费试用，首月10元

**Comment by doane2002cn** [comment]
有使用手册吗？v好像不好用，找不到

**Comment by azz212** [comment]
V 

> 有使用手册吗？v好像不好用，找不到

过期加个微:rongrong3938

**Comment by doane2002cn** [comment]
搜不到哈
